-name: print a parameter
 hosts: localhost
 connection: local
 tasks:
  - name: print a parameter
    ansible.builtin.debug
    msg: paramater- "{{ lookup('aws_ssm', 'test.test', region='us-east-1' ) }}"